services:
  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=sboard_task
    volumes:
      - postgres:/data

  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass A3UEbYaagT
    volumes:
      - redis:/data

  api:
    build: ./api
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

volumes:
  postgres:
    driver: local
  redis:
    driver: local
